from __future__ import annotations

from pathlib import Path

import yaml

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator
from agentroles.validators import AIDER_SLOT_NAMES

AIDER_SLOT_NAMES_INV: dict[str, str] = {v: k for k, v in AIDER_SLOT_NAMES.items()}


class AiderGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.AIDER

    def _build_conf(self, config: AgentRolesConfig, result: GenerationResult) -> dict:
        conf: dict = {}
        unmapped: list[str] = []
        mapped: dict[str, str] = {}

        for role_name, role_config in config.roles.items():
            if role_name in AIDER_SLOT_NAMES:
                slot = AIDER_SLOT_NAMES[role_name]
                conf[slot] = role_config.primary
                mapped[role_name] = slot
            else:
                unmapped.append(role_name)

        if unmapped:
            result.add_warning(
                f"Roles not representable in Aider (only 3 slots: --model, --editor-model, --weak-model): "
                f"{unmapped}. Convention: planner→model, implementer→editor-model, summarizer→weak-model."
            )

        if not conf:
            result.add_warning(
                "No standard Aider roles (planner, implementer, summarizer) found in config. "
                "Generated .aider.conf.yml will be empty."
            )

        return conf

    def generate(
        self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult
    ) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        conf = self._build_conf(config, result)

        target = base_dir / output_path
        target.parent.mkdir(parents=True, exist_ok=True)

        out = "# Generated by agentroles — source of truth: agentroles.yaml\n"
        out += (
            "# Maps: planner→model, implementer→editor-model, summarizer→weak-model\n"
        )
        out += yaml.dump(conf, default_flow_style=False, sort_keys=False)
        target.write_text(out)
        result.add_file(str(target))
