from __future__ import annotations

from pathlib import Path

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator

ROLE_MAP = {
    "planner": "provider",
    "implementer": "auto_suggestions_provider",
}


def _extract_provider(primary: str) -> str:
    return primary.split("/", 1)[0]


def _extract_model(primary: str) -> str:
    return primary.split("/", 1)[1] if "/" in primary else primary


class AvanteNvimGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.AVANTE_NVIM

    def _build_lua(self, config: AgentRolesConfig) -> str:
        provider_name = "openai"
        provider_model = "gpt-4o"
        autosuggest_provider = "openai"
        autosuggest_model = "gpt-4o-mini"

        for role_name, role_config in config.roles.items():
            if role_name == "planner":
                provider_name = _extract_provider(role_config.primary)
                provider_model = _extract_model(role_config.primary)
            elif role_name == "implementer":
                autosuggest_provider = _extract_provider(role_config.primary)
                autosuggest_model = _extract_model(role_config.primary)

        lua_lines: list[str] = [
            "-- Generated by agentroles — source of truth: agentroles.yaml",
            "-- Maps: planner→provider (main model), implementer→auto_suggestions_provider",
            "",
            "return {",
            '  "yetone/avante.nvim",',
            "  dependencies = {",
            '    "MunifTanjim/nui.nvim",',
            '    "nvim-lua/plenary.nvim",',
            '    "nvim-tree/nvim-web-devicons",',
            "  },",
            "  opts = {",
            f'    provider = "{provider_name}",',
            f'    provider_model = "{provider_model}",',
            f'    auto_suggestions_provider = "{autosuggest_provider}",',
            f'    auto_suggestions_model = "{autosuggest_model}",',
            "    behaviour = {",
            "      auto_suggestions = true,",
            "      auto_set_highlight_group = true,",
            "    },",
            "  },",
            "}",
        ]

        return "\n".join(lua_lines) + "\n"

    def generate(self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        lua_code = self._build_lua(config)

        target = base_dir / output_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(lua_code)
        result.add_file(str(target))
