from __future__ import annotations

import json
from pathlib import Path

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


def _toml_escape(value: str) -> str:
    return json.dumps(value)


class BitRouterGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.BITROUTER

    def _build_toml(self, config: AgentRolesConfig) -> str:
        header = "# Generated by agentroles — source of truth: agentroles.yaml\n"
        header += "# BitRouter context-aware agentic LLM gateway config\n\n"
        lines: list[str] = [header]

        for role_name, role_config in config.roles.items():
            provider, model_id = role_config.primary.split("/", 1)

            lines.append(f"[agents.{role_name}]")
            lines.append(f'name = "{role_name}"')
            lines.append(f'model = "{model_id}"')
            lines.append(f'provider = "{provider}"')

            if role_config.notes:
                lines.append(f"description = {_toml_escape(role_config.notes)}")

            if role_config.fallback:
                fallback_str = ", ".join(
                    _toml_escape(fb) for fb in role_config.fallback
                )
                lines.append(f"fallback_models = [{fallback_str}]")

            if role_config.max_cost_per_call_usd is not None:
                lines.append(f"max_cost = {role_config.max_cost_per_call_usd}")

            lines.append("")

        if config.observability.cost_tracking:
            lines.append("[cost_tracking]")
            lines.append("enabled = true")
            lines.append("")

        if config.observability.tag_calls_with_role:
            lines.append("[metadata]")
            lines.append('tags = ["agentroles"]')
            lines.append("tag_calls_with_role = true")
            lines.append("")

        return "\n".join(lines)

    def generate(
        self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult
    ) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        target = base_dir / output_path
        content = self._build_toml(config)

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        result.add_file(str(target))
