from __future__ import annotations

from pathlib import Path
from typing import Any

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


def _extract_provider(primary: str) -> str:
    return primary.split("/", 1)[0]


def _extract_model(primary: str) -> str:
    return primary.split("/", 1)[1] if "/" in primary else primary


ROLE_ADAPTER_MAP: dict[str, str] = {
    "planner": "anthropic",
    "implementer": "anthropic_fast",
    "reviewer": "openai",
    "tester": "anthropic_fast",
    "summarizer": "anthropic_fast",
}


class CodeCompanionNvimGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.CODECOMPANION_NVIM

    def _build_lua(self, config: AgentRolesConfig) -> str:
        adapters: dict[str, dict[str, Any]] = {}

        for role_name, role_config in config.roles.items():
            adapter_name = ROLE_ADAPTER_MAP.get(role_name, role_name)
            adapters[adapter_name] = {
                "name": _extract_provider(role_config.primary),
                "model": _extract_model(role_config.primary),
            }

        if "anthropic" not in adapters:
            adapters["anthropic"] = {"name": "anthropic", "model": "claude-sonnet-4-5"}
        if "openai" not in adapters:
            adapters["openai"] = {"name": "openai", "model": "gpt-4o"}
        if "anthropic_fast" not in adapters:
            adapters["anthropic_fast"] = {
                "name": "anthropic",
                "model": "claude-haiku-4-5",
            }

        adapter_blocks: list[str] = []
        for adapter_key, adapter_cfg in adapters.items():
            adapter_blocks.append(
                f"    {adapter_key} = function()\n"
                f'      return require("codecompanion.adapters").extend("{adapter_cfg["name"]}", {{\n'
                f"        env = {{\n"
                f'          model = "{adapter_cfg["model"]}",\n'
                f"        }},\n"
                f"      }})\n"
                f"    end,"
            )

        lua_lines: list[str] = [
            "-- Generated by agentroles — source of truth: agentroles.yaml",
            "-- Each role maps to a separate adapter profile in codecompanion.nvim",
            "",
            "return {",
            '  "olimorris/codecompanion.nvim",',
            "  dependencies = {",
            '    "nvim-lua/plenary.nvim",',
            '    "nvim-treesitter/nvim-treesitter",',
            "  },",
            "  opts = {",
            "    strategies = {",
            "      chat = {",
            '        adapter = "anthropic",',
            "      },",
            "      inline = {",
            '        adapter = "anthropic_fast",',
            "      },",
            "      cmd = {",
            '        adapter = "anthropic",',
            "      },",
            "    },",
            "    adapters = {",
            *adapter_blocks,
            "    },",
            "  },",
            "}",
        ]

        return "\n".join(lua_lines) + "\n"

    def generate(
        self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult
    ) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        lua_code = self._build_lua(config)

        target = base_dir / output_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(lua_code)
        result.add_file(str(target))
