from __future__ import annotations

from pathlib import Path

import yaml

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


class CodexCLIGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.CODEX_CLI

    def _extract_provider(self, model_id: str) -> str:
        return model_id.split("/", 1)[0]

    def _extract_model_name(self, model_id: str) -> str:
        parts = model_id.split("/", 1)
        return parts[1] if len(parts) > 1 else model_id

    def _build_config(self, config: AgentRolesConfig) -> dict:
        roles = config.roles
        if not roles:
            return {"model": ""}

        first_role = next(iter(roles.items()))
        first_name, first_config = first_role
        primary_model = self._extract_model_name(first_config.primary)

        result: dict = {
            "model": primary_model,
            "# model-selection": {
                "description": (
                    "Codex CLI supports a single model per session via --model CLI flag "
                    "or the model: key in .codex/config.yaml. Below is a reference mapping "
                    "of role → suggested model. Change the top-level model: field to switch."
                ),
            },
        }

        for role_name, role_config in roles.items():
            model_name = self._extract_model_name(role_config.primary)
            result[f"# role-{role_name}"] = model_name

        return result

    def generate(self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        target = base_dir / output_path
        conf = self._build_config(config)

        target.parent.mkdir(parents=True, exist_ok=True)
        out = "# Generated by agentroles — source of truth: agentroles.yaml\n"
        out += "# Codex CLI is single-model per session. Change model: below to switch roles.\n\n"
        out += yaml.dump(conf, default_flow_style=False, sort_keys=False, allow_unicode=True)
        target.write_text(out)
        result.add_file(str(target))
