from __future__ import annotations

from pathlib import Path

import yaml

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


CREW_PY_TEMPLATE = '''\
"""crew.py — Auto-generated CrewAI crew from agentroles.yaml.

This file loads agents defined in config/agents.yaml and tasks defined in
config/tasks.yaml and assembles them into a CrewAI Crew.

Usage:
    python crew.py
"""

from crewai import Agent, Crew, Task

from config.agents import AGENTS
from config.tasks import TASKS

agents = [Agent(**a) for a in AGENTS]
tasks = [Task(**t) for t in TASKS]

crew = Crew(
    agents=agents,
    tasks=tasks,
)
crew.kickoff()
'''


class CrewAIGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.CREWAI

    def _build_agents(self, config: AgentRolesConfig) -> list[dict]:
        agents: list[dict] = []
        for role_name, role_config in config.roles.items():
            agent: dict = {
                "role": role_name,
                "goal": f"Execute the {role_name} function using AI assistance",
                "backstory": role_config.notes
                or f"An AI agent specialized in the {role_name} role",
                "llm": role_config.primary,
            }
            agents.append(agent)
        return agents

    def _build_tasks(self, config: AgentRolesConfig) -> list[dict]:
        tasks: list[dict] = []
        for role_name in config.roles:
            task: dict = {
                "description": f"Task for the {role_name} agent",
                "expected_output": f"Output from the {role_name} agent",
                "agent": role_name,
            }
            tasks.append(task)
        return tasks

    def _generate_agents_yaml(
        self, config: AgentRolesConfig, agents_dir: Path, result: GenerationResult
    ) -> None:
        agents = self._build_agents(config)
        agents_dir.mkdir(parents=True, exist_ok=True)
        agents_path = agents_dir / "agents.yaml"
        header = "# Generated by agentroles — source of truth: agentroles.yaml\n"
        header += "# https://docs.crewai.com/core-concepts/Agents/\n"
        content = (
            header
            + "\n"
            + yaml.dump(
                agents, default_flow_style=False, sort_keys=False, allow_unicode=True
            )
        )
        agents_path.write_text(content)
        result.add_file(str(agents_path))

    def _generate_tasks_yaml(
        self, config: AgentRolesConfig, agents_dir: Path, result: GenerationResult
    ) -> None:
        tasks = self._build_tasks(config)
        agents_dir.mkdir(parents=True, exist_ok=True)
        tasks_path = agents_dir / "tasks.yaml"
        header = "# Generated by agentroles — source of truth: agentroles.yaml\n"
        header += "# https://docs.crewai.com/core-concepts/Tasks/\n"
        content = (
            header
            + "\n"
            + yaml.dump(
                tasks, default_flow_style=False, sort_keys=False, allow_unicode=True
            )
        )
        tasks_path.write_text(content)
        result.add_file(str(tasks_path))

    def _generate_crew_py(
        self,
        config: AgentRolesConfig,
        base_dir: Path,
        output_dir: Path,
        result: GenerationResult,
    ) -> None:
        crew_path = output_dir / "crew.py"
        crew_path.write_text(CREW_PY_TEMPLATE)
        result.add_file(str(crew_path))

    def generate(
        self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult
    ) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        target = base_dir / output_path
        agents_dir = target / "config"

        self._generate_agents_yaml(config, agents_dir, result)
        self._generate_tasks_yaml(config, agents_dir, result)
        self._generate_crew_py(config, base_dir, target, result)
