from __future__ import annotations

import json
from pathlib import Path

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


class CrushGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.CRUSH

    def _extract_provider(self, model_id: str) -> str:
        return model_id.split("/", 1)[0]

    def _extract_model_name(self, model_id: str) -> str:
        parts = model_id.split("/", 1)
        return parts[1] if len(parts) > 1 else model_id

    def _api_key_env(self, provider: str) -> str:
        env_map: dict[str, str] = {
            "openai": "$OPENAI_API_KEY",
            "anthropic": "$ANTHROPIC_API_KEY",
            "google": "$GOOGLE_API_KEY",
            "gemini": "$GEMINI_API_KEY",
            "groq": "$GROQ_API_KEY",
            "deepseek": "$DEEPSEEK_API_KEY",
            "cohere": "$CO_API_KEY",
            "mistral": "$MISTRAL_API_KEY",
            "xai": "$XAI_API_KEY",
            "perplexity": "$PERPLEXITY_API_KEY",
            "together": "$TOGETHER_API_KEY",
            "openrouter": "$OPENROUTER_API_KEY",
        }
        return env_map.get(provider.lower(), f"${provider.upper()}_API_KEY")

    def _build_config(self, config: AgentRolesConfig) -> dict:
        roles = config.roles
        providers: dict[str, dict] = {}
        role_model_map: dict[str, dict] = {}

        for role_name, role_config in roles.items():
            provider = self._extract_provider(role_config.primary)
            model_name = self._extract_model_name(role_config.primary)
            provider_key = provider.lower()

            if provider_key not in providers:
                providers[provider_key] = {
                    "name": provider,
                    "api_key": self._api_key_env(provider),
                    "models": [],
                }

            model_entry = {"name": model_name, "roles": [role_name]}
            existing = [m for m in providers[provider_key]["models"] if m["name"] == model_name]
            if not existing:
                providers[provider_key]["models"].append(model_entry)
            else:
                existing[0]["roles"].append(role_name)

            role_model_map[role_name] = {
                "provider": provider_key,
                "model": model_name,
            }

        return {
            "providers": providers,
            "role_model_map": role_model_map,
        }

    def generate(self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        target = base_dir / output_path
        conf = self._build_config(config)

        target.parent.mkdir(parents=True, exist_ok=True)

        out = {
            "_comment": "Generated by agentroles — source of truth: agentroles.yaml",
            "_note": "Crush supports session-based model switching. Use the --model flag or select via UI.",
            **conf,
        }

        target.write_text(json.dumps(out, indent=2) + "\n")
        result.add_file(str(target))
