from __future__ import annotations

from pathlib import Path

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator

ROLE_PROVIDER_MAP: dict[str, str] = {
    "planner": "ellama-coding-provider",
    "implementer": "ellama-coding-provider",
    "reviewer": "ellama-summarization-provider",
    "tester": "ellama-extraction-provider",
    "summarizer": "ellama-summarization-provider",
}


def _elisp_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


class EllamaGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.ELLAMA

    def _build_elisp(self, config: AgentRolesConfig) -> str:
        provider_defs: list[str] = []
        for role_name, role_config in config.roles.items():
            provider_name = ROLE_PROVIDER_MAP.get(role_name, "ellama-provider")
            provider_defs.append(
                f"  (setq {provider_name}\n"
                f"        (make-llm-ellama\n"
                f"         :chat-model {_elisp_str(role_config.primary)}\n"
                f"         :embedding-model {_elisp_str(role_config.primary)}))"
            )

        if not provider_defs:
            provider_defs.append(
                "  (setq ellama-provider\n"
                "        (make-llm-ellama\n"
                '         :chat-model "claude-sonnet-4-5"\n'
                '         :embedding-model "claude-sonnet-4-5"))'
            )

        provider_blocks = "\n".join(provider_defs)

        elisp = f"""\
;; Generated by agentroles — source of truth: agentroles.yaml
;; Ellama uses separate providers per function (coding, summarization, translation, extraction, completion)

(use-package ellama
  :ensure t
  :init
{provider_blocks}
  :config
  (setopt ellama-sessions-directory (expand-file-name "ellama-sessions" user-emacs-directory))
  (setopt ellama-keymap-prefix "C-c e"))
"""

        return elisp

    def generate(self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        elisp_code = self._build_elisp(config)

        target = base_dir / output_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(elisp_code)
        result.add_file(str(target))
