from __future__ import annotations

from pathlib import Path

import yaml

from agentroles.models import AgentRolesConfig, RoleConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


class FactoryGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.FACTORY

    def _build_droid_entry(self, role_name: str, role_config: RoleConfig) -> dict:
        droid: dict = {
            "name": role_name,
            "description": role_config.notes or f"AI droid for the {role_name} role",
            "model": role_config.primary,
        }

        if role_config.fallback:
            droid["fallback_models"] = role_config.fallback

        if role_config.max_cost_per_call_usd is not None:
            droid["max_cost_per_call"] = role_config.max_cost_per_call_usd

        return droid

    def generate(
        self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult
    ) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        target = base_dir / output_path

        droids: list[dict] = []
        for role_name, role_config in config.roles.items():
            droids.append(self._build_droid_entry(role_name, role_config))

        cfg: dict = {
            "droids": droids,
        }

        if config.observability.cost_tracking:
            cfg["cost_tracking"] = {"enabled": True}

        target.parent.mkdir(parents=True, exist_ok=True)

        header = "# Generated by agentroles — source of truth: agentroles.yaml\n"
        header += "# Factory droid configuration — per-role model assignments\n\n"

        content = header + yaml.dump(
            cfg, default_flow_style=False, sort_keys=False, allow_unicode=True
        )
        target.write_text(content)
        result.add_file(str(target))
