from __future__ import annotations

import json
from pathlib import Path

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


class GeminiCLIGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.GEMINI_CLI

    def _extract_provider(self, model_id: str) -> str:
        return model_id.split("/", 1)[0]

    def _extract_model_name(self, model_id: str) -> str:
        parts = model_id.split("/", 1)
        return parts[1] if len(parts) > 1 else model_id

    def _build_config(self, config: AgentRolesConfig) -> dict:
        roles = config.roles
        if not roles:
            return {"model": "", "providers": {}}

        first_role = next(iter(roles.items()))
        first_name, first_config = first_role
        provider = self._extract_provider(first_config.primary)
        model_name = self._extract_model_name(first_config.primary)

        providers: dict[str, dict] = {}
        for role_name, role_config in roles.items():
            p = self._extract_provider(role_config.primary)
            m = self._extract_model_name(role_config.primary)
            provider_name = p.lower()

            if provider_name not in providers:
                providers[provider_name] = {
                    "name": p,
                    "models": [],
                    "env_api_key": self._api_key_env(p),
                }
            if m not in providers[provider_name]["models"]:
                providers[provider_name]["models"].append(m)

        # Build role reference map
        role_ref: dict[str, str] = {}
        for role_name, role_config in roles.items():
            role_ref[f"_role_{role_name}"] = (
                f"Uses {self._extract_model_name(role_config.primary)} "
                f"({self._extract_provider(role_config.primary)})"
            )

        return {
            "model": model_name,
            "provider": provider,
            "providers": providers,
            "roles_reference": role_ref,
        }

    def _api_key_env(self, provider: str) -> str:
        env_map: dict[str, str] = {
            "openai": "$OPENAI_API_KEY",
            "anthropic": "$ANTHROPIC_API_KEY",
            "google": "$GOOGLE_API_KEY",
            "gemini": "$GEMINI_API_KEY",
            "groq": "$GROQ_API_KEY",
            "deepseek": "$DEEPSEEK_API_KEY",
            "cohere": "$CO_API_KEY",
            "mistral": "$MISTRAL_API_KEY",
            "together": "$TOGETHER_API_KEY",
            "openrouter": "$OPENROUTER_API_KEY",
        }
        return env_map.get(provider.lower(), f"${provider.upper()}_API_KEY")

    def generate(
        self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult
    ) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        target = base_dir / output_path
        conf = self._build_config(config)

        target.parent.mkdir(parents=True, exist_ok=True)

        out = {
            "_comment": "Generated by agentroles — source of truth: agentroles.yaml",
            "_note": "Gemini CLI supports a single model per session. Edit the model field to switch roles.",
            **conf,
        }

        target.write_text(json.dumps(out, indent=2) + "\n")
        result.add_file(str(target))
