from __future__ import annotations

from pathlib import Path

import yaml

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


class GooseGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.GOOSE

    def _extract_provider(self, model_id: str) -> str:
        return model_id.split("/", 1)[0]

    def _extract_model_name(self, model_id: str) -> str:
        parts = model_id.split("/", 1)
        return parts[1] if len(parts) > 1 else model_id

    def _api_key_env(self, provider: str) -> str:
        env_map: dict[str, str] = {
            "openai": "$OPENAI_API_KEY",
            "anthropic": "$ANTHROPIC_API_KEY",
            "google": "$GOOGLE_API_KEY",
            "gemini": "$GEMINI_API_KEY",
            "groq": "$GROQ_API_KEY",
            "deepseek": "$DEEPSEEK_API_KEY",
            "cohere": "$CO_API_KEY",
            "mistral": "$MISTRAL_API_KEY",
            "xai": "$XAI_API_KEY",
            "perplexity": "$PERPLEXITY_API_KEY",
            "together": "$TOGETHER_API_KEY",
            "openrouter": "$OPENROUTER_API_KEY",
            "ollama": "http://localhost:11434",
            "lmstudio": "http://localhost:1234",
        }
        return env_map.get(provider.lower(), "${API_KEY}")

    def _build_config(self, config: AgentRolesConfig) -> dict:
        roles = config.roles
        providers: dict[str, dict] = {}
        role_assignments: dict[str, dict] = {}

        for role_name, role_config in roles.items():
            provider = self._extract_provider(role_config.primary)
            model_name = self._extract_model_name(role_config.primary)
            provider_key = provider.lower()

            providers[provider_key] = {
                "type": provider_key,
                "api_key": self._api_key_env(provider),
                "default_model": model_name,
            }

            role_assignments[role_name] = {
                "provider": provider_key,
                "model": model_name,
                "description": role_config.notes or f"{role_name} role",
            }

        first_role = next(iter(roles.items())) if roles else (None, None)
        default_provider = None
        default_model = None
        if first_role[1] is not None:
            default_provider = self._extract_provider(first_role[1].primary).lower()
            default_model = self._extract_model_name(first_role[1].primary)

        return {
            "default": {
                "provider": default_provider or "",
                "model": default_model or "",
            },
            "providers": providers,
            "roles": role_assignments,
        }

    def generate(self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        target = base_dir / output_path
        conf = self._build_config(config)

        target.parent.mkdir(parents=True, exist_ok=True)

        out = "# Generated by agentroles — source of truth: agentroles.yaml\n"
        out += "# Goose supports multiple providers. See https://block.github.io/goose/ for details.\n\n"
        out += yaml.dump(conf, default_flow_style=False, sort_keys=False, allow_unicode=True)
        target.write_text(out)
        result.add_file(str(target))
