from __future__ import annotations

from pathlib import Path

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


def _extract_provider(primary: str) -> str:
    return primary.split("/", 1)[0]


def _extract_model(primary: str) -> str:
    return primary.split("/", 1)[1] if "/" in primary else primary


def _elisp_str(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _provider_to_gptel_backend(provider: str) -> str:
    mappings = {
        "openai": "gpt",
        "anthropic": "claude",
        "google": "gemini",
        "mistral": "mistral",
    }
    return mappings.get(provider, provider)


class GptelGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.GPTEL

    def _build_elisp(self, config: AgentRolesConfig) -> str:
        backend_defs: list[str] = []
        backend_names: list[str] = []

        for role_name, role_config in config.roles.items():
            provider = _extract_provider(role_config.primary)
            model_id = _extract_model(role_config.primary)
            backend = _provider_to_gptel_backend(provider)
            backend_name = f"agentroles-{role_name}"

            backend_names.append(backend_name)
            backend_defs.append(
                f"(defvar {backend_name}\n"
                f'  (gptel-make-{backend} "{backend.capitalize()}"\n'
                f'    :key (gptel-api-key-from-auth-source "api.{provider}.com")\n'
                f'    :models (list {_elisp_str(model_id)})\n'
                f'    :stream t))'
            )

        if not backend_defs:
            backend_defs.append(
                '(defvar agentroles-default\n'
                '  (gptel-make-openai "GPT"\n'
                '    :key (gptel-api-key-from-auth-source "api.openai.com")\n'
                '    :models (list "gpt-4o")\n'
                '    :stream t))'
            )
            backend_names.append("agentroles-default")

        backend_blocks = "\n\n".join(backend_defs)
        backend_list = "\n  ".join(f'"{n}"' for n in backend_names)

        elisp = f"""\
;; Generated by agentroles — source of truth: agentroles.yaml
;; gptel uses one backend per provider/model combination with gptel-make-* functions

{backend_blocks}

(defvar agentroles-backends
  (list {backend_list})
  "Backends generated by agentroles for per-role model assignment.")

;; Use M-x gptel-menu to switch between these backends at runtime.
(provide 'agentroles-gptel)
"""

        return elisp

    def generate(self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        elisp_code = self._build_elisp(config)

        target = base_dir / output_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(elisp_code)
        result.add_file(str(target))
