from __future__ import annotations

from pathlib import Path

import yaml

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


class InferMuxGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.INFERMUX

    def _build_routes(self, config: AgentRolesConfig) -> list[dict]:
        routes: list[dict] = []
        for role_name, role_config in config.roles.items():
            provider, model_id = role_config.primary.split("/", 1)
            route: dict = {
                "role": role_name,
                "provider": provider,
                "model": model_id,
                "route_name": f"role-{role_name}",
            }

            if role_config.fallback:
                route["fallback"] = role_config.fallback

            if role_config.max_cost_per_call_usd is not None:
                route["max_cost_per_call_usd"] = role_config.max_cost_per_call_usd

            routes.append(route)
        return routes

    def generate(self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        target = base_dir / output_path

        routes = self._build_routes(config)
        cfg: dict = {
            "version": 1,
            "source": "agentroles.yaml",
            "model_routes": routes,
        }

        if config.observability.cost_tracking:
            cfg["observability"] = {"cost_tracking": True}

        target.parent.mkdir(parents=True, exist_ok=True)

        header = "# Generated by agentroles — source of truth: agentroles.yaml\n"
        header += "# Infermux multi-provider router config\n\n"

        content = header + yaml.dump(cfg, default_flow_style=False, sort_keys=False, allow_unicode=True)
        target.write_text(content)
        result.add_file(str(target))
