from __future__ import annotations

from pathlib import Path

import yaml

from agentroles.models import AgentRolesConfig, RoleConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


class LiteLLMGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.LITELLM_PROXY

    def _build_model_entry(
        self,
        role_name: str,
        role_config: RoleConfig,
        config: AgentRolesConfig,
    ) -> dict:
        litellm_params: dict = {
            "model": role_config.primary,
            "metadata": {
                "role": role_name,
                "tags": ["agentroles", role_name],
            },
        }

        if role_config.max_cost_per_call_usd is not None:
            litellm_params["max_cost_per_call_usd"] = role_config.max_cost_per_call_usd

        entry: dict = {
            "model_name": f"role-{role_name}",
            "litellm_params": litellm_params,
        }

        if role_config.fallback:
            entry["fallbacks"] = [f"role-{role_name}-fallback-{i}" for i in range(len(role_config.fallback))]

        return entry

    def _build_fallback_entries(
        self,
        role_name: str,
        role_config: RoleConfig,
    ) -> list[dict]:
        entries: list[dict] = []
        for i, fb_model in enumerate(role_config.fallback):
            entries.append({
                "model_name": f"role-{role_name}-fallback-{i}",
                "litellm_params": {
                    "model": fb_model,
                    "metadata": {
                        "role": role_name,
                        "tags": ["agentroles", role_name, "fallback"],
                    },
                },
            })
        return entries

    def _build_config(self, config: AgentRolesConfig) -> dict:
        model_list: list[dict] = []

        for role_name, role_config in config.roles.items():
            model_list.append(self._build_model_entry(role_name, role_config, config))
            model_list.extend(self._build_fallback_entries(role_name, role_config))

        proxy_config: dict = {
            "model_list": model_list,
        }

        routing_mode = config.routing.mode.value if hasattr(config.routing.mode, 'value') else str(config.routing.mode)
        dynamic_config = config.routing.dynamic

        if routing_mode == "dynamic" and dynamic_config.enabled:
            proxy_config["router_settings"] = {
                "routing_strategy": "cache-aware-static",
                "num_retries": 2,
                "cooldown_time": 30,
                "allowed_fails": 3,
            }

        if config.observability.tag_calls_with_role:
            proxy_config.setdefault("litellm_settings", {})
            proxy_config["litellm_settings"]["metadata"] = {
                "tag_calls_with_role": True,
            }

        if config.observability.cost_tracking:
            proxy_config.setdefault("litellm_settings", {})
            proxy_config["litellm_settings"]["success_callback"] = ["prometheus"] if "prometheus" not in proxy_config.get("litellm_settings", {}).get("success_callback", []) else proxy_config["litellm_settings"]["success_callback"]

        return proxy_config

    def generate(self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        proxy_config = self._build_config(config)

        target = base_dir / output_path
        target.parent.mkdir(parents=True, exist_ok=True)

        out = "# Generated by agentroles — source of truth: agentroles.yaml\n"
        out += "# This is a LiteLLM proxy config. Start with:\n"
        out += "#   litellm --config litellm-config.yaml\n"
        out += yaml.dump(proxy_config, default_flow_style=False, sort_keys=False, allow_unicode=True)
        target.write_text(out)
        result.add_file(str(target))
