from __future__ import annotations

from pathlib import Path

import yaml

from agentroles.models import AgentRolesConfig, RoleConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


METAGPT_ROLE_MAP: dict[str, str] = {
    "planner": "PM",
    "architect": "Architect",
    "implementer": "Engineer",
    "tester": "QA",
    "reviewer": "Reviewer",
    "pm": "PM",
    "qa": "QA",
    "engineer": "Engineer",
}

METAGPT_DEFAULT_ROLE = "Engineer"


class MetaGPTGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.METAGPT

    def _build_llm_config(self, role_name: str, role_config: RoleConfig) -> dict:
        provider, model_id = role_config.primary.split("/", 1)
        api_type = "openai"
        if provider == "anthropic":
            api_type = "anthropic"
        elif provider == "openai":
            api_type = "openai"
        elif provider == "azure":
            api_type = "azure"

        llm: dict = {
            "api_type": api_type,
            "model": model_id,
            "base_url": "https://api.openai.com/v1",
            "api_key": "YOUR_API_KEY",
        }
        return llm

    def _build_config(self, config: AgentRolesConfig, result: GenerationResult) -> dict:
        cfg: dict = {}
        unmapped: list[str] = []

        for role_name, role_config in config.roles.items():
            mg_role = METAGPT_ROLE_MAP.get(role_name.lower(), None)
            if mg_role is None:
                unmapped.append(role_name)
                mg_role = f"Custom_{role_name}"

            llm_config = self._build_llm_config(role_name, role_config)
            cfg[mg_role] = {"llm": llm_config}

        if unmapped:
            result.add_warning(
                f"Roles not in standard MetaGPT mapping (PM, Architect, Engineer, QA): {unmapped}. "
                f"Roles will be mapped as custom entries."
            )

        return cfg

    def generate(self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        target = base_dir / output_path
        meta_cfg = self._build_config(config, result)

        target.parent.mkdir(parents=True, exist_ok=True)

        header = "# Generated by agentroles — source of truth: agentroles.yaml\n"
        header += "# MetaGPT config2.yaml — per-role LLM configuration\n"
        header += "# See: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html\n\n"

        content = header + yaml.dump(meta_cfg, default_flow_style=False, sort_keys=False, allow_unicode=True)
        target.write_text(content)
        result.add_file(str(target))
