from __future__ import annotations

import json
from pathlib import Path

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


class OpenInterpreterGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.OPENINTERPRETER

    def _extract_provider(self, model_id: str) -> str:
        return model_id.split("/", 1)[0]

    def _extract_model_name(self, model_id: str) -> str:
        parts = model_id.split("/", 1)
        return parts[1] if len(parts) > 1 else model_id

    def _api_key_env(self, provider: str) -> str:
        env_map: dict[str, str] = {
            "openai": "$OPENAI_API_KEY",
            "anthropic": "$ANTHROPIC_API_KEY",
            "google": "$GOOGLE_API_KEY",
            "gemini": "$GEMINI_API_KEY",
            "groq": "$GROQ_API_KEY",
            "deepseek": "$DEEPSEEK_API_KEY",
            "cohere": "$CO_API_KEY",
            "mistral": "$MISTRAL_API_KEY",
            "together": "$TOGETHER_API_KEY",
            "openrouter": "$OPENROUTER_API_KEY",
        }
        return env_map.get(provider.lower(), f"${provider.upper()}_API_KEY")

    def _build_config(self, config: AgentRolesConfig) -> dict:
        roles = config.roles
        role_preferences: dict[str, dict] = {}

        if not roles:
            return {"model_preferences": {}, "default_model": ""}

        for role_name, role_config in roles.items():
            provider = self._extract_provider(role_config.primary)
            model_name = self._extract_model_name(role_config.primary)
            key_env = self._api_key_env(provider)

            role_preferences[role_name] = {
                "model": model_name,
                "provider": provider,
                "api_key": key_env,
                "notes": role_config.notes or f"{role_name} role",
            }

            if role_config.fallback:
                role_preferences[role_name]["fallback"] = [
                    self._extract_model_name(fb) for fb in role_config.fallback
                ]

        first_role = next(iter(roles))
        first_config = roles[first_role]

        return {
            "default_model": self._extract_model_name(first_config.primary),
            "model_preferences": role_preferences,
        }

    def generate(self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        target = base_dir / output_path
        conf = self._build_config(config)

        target.parent.mkdir(parents=True, exist_ok=True)

        out = {
            "_comment": "Generated by agentroles — source of truth: agentroles.yaml",
            "_note": "OpenInterpreter is a fork of Codex. This config maps roles to models. "
                     "Use --model to switch at runtime.",
            **conf,
        }

        target.write_text(json.dumps(out, indent=2) + "\n")
        result.add_file(str(target))
