from __future__ import annotations

from pathlib import Path

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


OPENHANDS_PROFILE_TEMPLATE = """\
# Generated by agentroles — source of truth: agentroles.yaml

[llm.{role_key}]
model = "{model}"
api_key = "${{LLM_API_KEY}}"
"""


class OpenHandsGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.OPENHANDS

    def _build_toml(self, config: AgentRolesConfig) -> str:
        header = "# Generated by agentroles — source of truth: agentroles.yaml\n\n"
        lines: list[str] = [header]

        for role_name, role_config in config.roles.items():
            role_key = role_name.replace(" ", "-").lower()

            lines.append(f"[llm.{role_key}]")
            lines.append(f'model = "{role_config.primary}"')
            lines.append('api_key = "${{LLM_API_KEY}}"')

            if role_config.notes:
                lines.append(f'# notes: {role_config.notes}')

            lines.append("")

        return "\n".join(lines)

    def generate(self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult) -> None:
        output_path = config.get_target_path(self.target_type)
        if not output_path:
            return

        target = base_dir / output_path
        content = self._build_toml(config)

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)
        result.add_file(str(target))
