from __future__ import annotations

from pathlib import Path

from agentroles.models import AgentRolesConfig, TargetType
from agentroles.plugin import GenerationResult, TargetGenerator


class QwenCodeGenerator(TargetGenerator):
    @property
    def target_type(self) -> TargetType:
        return TargetType.QWEN_CODE

    def _extract_model_name(self, model_id: str) -> str:
        parts = model_id.split("/", 1)
        return parts[1] if len(parts) > 1 else model_id

    def _build_agent_markdown(
        self, role_name: str, role_config, config: AgentRolesConfig
    ) -> str:
        model_name = self._extract_model_name(role_config.primary)
        notes = role_config.notes or f"{role_name} agent — generated by agentroles"
        description = notes[:200]

        frontmatter: dict = {
            "name": role_name,
            "description": description,
            "model": model_name,
        }

        if role_config.fallback:
            frontmatter["fallback_models"] = [
                self._extract_model_name(fb) for fb in role_config.fallback
            ]

        lines: list[str] = ["---"]
        for key, value in frontmatter.items():
            if isinstance(value, list):
                lines.append(f"{key}:")
                for item in value:
                    lines.append(f"  - {item}")
            else:
                lines.append(f"{key}: {value}")
        lines.append("---")
        lines.append("")
        lines.append(f"# {role_name.title()} Agent")
        lines.append("# Generated by agentroles — source of truth: agentroles.yaml")
        lines.append(f"# Qwen Code subagent — place in .qwen/agents/{role_name}.md")
        lines.append("")
        lines.append(f"You are the **{role_name}** agent. {notes}")

        return "\n".join(lines) + "\n"

    def generate(
        self, config: AgentRolesConfig, base_dir: Path, result: GenerationResult
    ) -> None:
        output_dir = config.get_target_path(self.target_type)
        if not output_dir:
            return

        target_dir = base_dir / output_dir
        target_dir.mkdir(parents=True, exist_ok=True)

        for role_name, role_config in config.roles.items():
            markdown = self._build_agent_markdown(role_name, role_config, config)
            file_path = target_dir / f"{role_name}.md"
            file_path.write_text(markdown)
            result.add_file(str(file_path))
